version: 2

sources:
  - name: staging
    database: tmhomework
    schema: sample
    tables:
      - name: remote_work_impact
      - name: student_performance

models:
  - name: stg_student_private
    description: "students who studies in a private school"
    columns:
      - name: motivation_level
        description: "level of student motivation in school"
      - name: attendance
        description: "number of days when student is present"
      - name: access_to_resources
        description: "how much does student have access to vital resources"
      - name: peer_influence
        description: "level of peer influence on student"
  - name: stg_remote_data_job
    description: "effect of remote work on data professionals"
  - name: stg_student_w_id
    description: "student base table with id column"